### ISSUE TITLE
To-do list

### ISSUE THREAD

**Issue by TechWhizZ199** [TechWhizZ199/pinybot#18]
Here is a list of items to test out or implement:

- [ ] Make do_pause_media & do_resume_media functions work on all times (after consecutive tries they incorrectly resume at the wrong time). New class?
- [ ] Wildcard (via regex module) support for banning nicknames, banning strings & auto forgives.
- [ ] Make sure the !rm command works fine. Try testing it out.
- [ ] Try getting cauth cookie working for all accounts; login to suspended accounts - get cauth cookie without proper JSON formatting.
- [ ] Test out how bot handles multiple media playing at the same time and what the bot gives priority to (will be the one which plays first - should be).
- [ ] MySQL DB? For each room data. (sqlite3?) - MySQL db for bot data and specific config.ini for each room, all in a new folder.
- [ ] Automatic broadcast request acceptance for those waiting in the greenroom.
- [ ] YouTube unicode (unicode input via !yt) search support - format via encode using ord?
- [ ] Camera close command which regex support to allow any string e.g. newuser* would close anyone with newuser followed by any alphanumeric characters.
- [ ] Playlist editing (replace/ searching current playlist).
- [ ] Make !time return a 24 hour output instead of just 12 hour, and have AM or PM at the end of the time. (Make it say 12 hour time ?) as stated in #17 .
- [ ] Sort out the Akinator/Votekick module into other files or organise them better so they do not take as much space.
- [ ] RSS Feed compatibility & News feed compatibility (possibily for debating rooms !debate returns new topic to talk about) - new list every now and again.
- [ ] Duck Go/ Wikipedia (wikipedia search results handling) better functionality.
- [ ] More custom unicode(?) - custom unicode - http://text-symbols.com/cool/#all_cats
- [ ] Report sending fix (?) - report a user.
- [ ] Vibrant console (via colorama(?)- e.g. RoomB0T
- [ ] !topicis (says the room topic) command.
- [ ] Confirm issue: do_media_pause: its also a problem if someone enters a room AFTER a video has been paused.
- [ ] Timestamp on all messages and pm messages.
- [ ] Make code cleaner (remove use of try/except in specific) in do_stop_private_media.
- [ ]  Add 'Not Enabled' notices on all appropriate functions.

**Comment by nortxort** [comment]
I see that you have "Automatic broadcast request acceptance for those waiting in the greenroom."
on your list of to-dos. I think this will be problematic for a couple of reasons.

* As far as i can tell there is no way of telling when a user is actually waiting in the greenroom.
So how would you know when to send the broadcast approval message? assuming you want it to be automatic. Also, why enable greenroom if the bot approves anyone?

* You could make a command for it. So a user could issue a command, and then have the bot send the approval message. However this takes away the need of greenroom in the first place, assuming any user could trigger the command. And even with this approach and the right user permissions in place, you still don't know if the user is in the greenroom waiting, so the bot could be sending approval messages to users not even on cam/waiting.

* If the bot was in a room(as moderator) and that room did NOT have greenroom enabled when it joined, but had greenroom enabled at a later time, then the bot would not have the bpassword and greenroom would be False.

**Comment by TechWhizZ199** [comment]
@nortxort 
> no way of telling when a user is actually waiting in the greenroom.
I agree, this did occur to me as the main problem amongst the several others, though all in all I only wanted to place this command in just to satisfy the library. You may argue there is no point if it not going to be used, however if someone else finds a use for it then I am quite alright placing it in.

Points 2/3 you are absolutely correct, it does make the method to accept it redundant and we can not know if the room has been moved to greenroom as the bpassword is requested upon joining. Though I am still yet to see how the actual greenroom acceptance works for moderators, since if  you imagine the bot as a moderator, how does the bot know when greenroom is in place?
